Specify the install step in README
Otherwise the test command won't wok:

```
$ npm test

> heroku-docker@0.0.21 test /Users/srid/code/heroku-docker
> mocha --timeout 30000

sh: mocha: command not found
npm ERR! Test failed.  See above for more details.
```

After install mocha:

```
$ npm test

> heroku-docker@0.0.21 test /Users/srid/code/heroku-docker
> mocha --timeout 30000


module.js:340
    throw err;
          ^
Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/srid/code/heroku-docker/test/fixtures.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! Test failed.  See above for more details.
```

Oh wait, there is `package.json` in the project. So I should be running `npm install`. This is not clear in the README.